In [1]:
import cv2
import numpy as np

# Load the image data using OpenCV
image_data = cv2.imread("DATASET/1/5.png")

# Convert the image data to a numpy array
image_array = np.array(image_data)


In [12]:
from skimage.feature import hog

def create_hog_features(image_data):
    hog_features = []
    for image in image_data:
        hog_features.append(hog(image, orientations=8, pixels_per_cell=(16, 16), cells_per_block=(1, 1)))
    return hog_features


In [13]:
print(image_data)

[[[121 139 138]
  [121 138 138]
  [122 135 136]
  ...
  [154 156 143]
  [155 157 144]
  [155 157 144]]

 [[128 144 144]
  [126 140 140]
  [127 138 139]
  ...
  [154 156 144]
  [153 155 143]
  [151 153 141]]

 [[130 139 140]
  [126 135 136]
  [126 133 135]
  ...
  [157 158 149]
  [156 157 148]
  [154 154 147]]

 ...

 [[119 127 130]
  [121 129 132]
  [123 131 135]
  ...
  [ 11  14   6]
  [ 11  14   6]
  [ 12  15   7]]

 [[121 127 130]
  [122 128 131]
  [124 129 134]
  ...
  [ 11  13   7]
  [ 10  12   6]
  [ 11  13   8]]

 [[122 127 130]
  [122 126 130]
  [123 127 132]
  ...
  [ 12  13   9]
  [  9  10   7]
  [  8   9   6]]]


In [1]:
def create_features(image_paths):
    features = []
    labels = []
    for path in image_paths:
        # Load the image data using OpenCV
        image_data = cv2.imread(path)

        # Convert the image data to a numpy array
        image_array = np.array(image_data)

        # Preprocess the data (resize, normalize, etc.)
        image_array = image_array / 255.0

        # Extract HOG features
        hog_features = hog(image_array, orientations=8, pixels_per_cell=(16, 16), cells_per_block=(1, 1))

        # Extract LBP features
        lbp_features = local_binary_pattern(image_array, 8, 1, method='uniform')
        
        # Create a color histogram feature
        gray_image = rgb2gray(image_array)
        hist, _ = histogram(gray_image)

        # Combine features
        combined_features = np.concatenate((hog_features, lbp_features, hist))

        # Normalize features
        normalized_features = (combined_features - np.mean(combined_features)) / np.std(combined_features)

        # Append to the list of features
        features.append(normalized_features)

        # Append the label
        labels.append(path.split("/")[-2])
    return features, labels


In [8]:
import numpy as np
import imageio
from skimage.feature import hog
from skimage.feature import local_binary_pattern
from skimage.color import rgb2gray
from skimage.exposure import histogram
import matplotlib.pyplot as plt
%matplotlib inline

def create_features(image_paths):
    features = []
    labels = []
    for path in image_paths:
        # Load the image data using imageio
        image_data = cv2.imread("DATASET/1/10.png")

        # Convert the image data to a numpy array
        image_array = np.array(image_data)

        # Convert the image data to a numpy array
        image_array = np.array(image_data)
        plt.imshow(image_array)
        plt.show()
        # Preprocess the data (resize, normalize, etc.)
        image_array = image_array / 255.0

        try:
            cv2.imshow("image", image_array) 
            plt.imshow(image_array) 
            plt.show() # cv2.imshow("image", image_array)
            cv2.waitKey(0)
            cv2.destroyAllWindows()
        except SystemError:
            print("Could not display the image, please check your display settings.")
            

        # Extract HOG features
        hog_features = hog(image_array, orientations=8, pixels_per_cell=(16, 16), cells_per_block=(1, 1))

        # Extract LBP features
        lbp_features = local_binary_pattern(image_array, 8, 1, method='uniform')
        
        # Create a color histogram feature
        gray_image = rgb2gray(image_array)
        hist, _ = histogram(gray_image)

        # Combine features
        combined_features = np.concatenate((hog_features, lbp_features, hist))

        # Normalize features
        normalized_features = (combined_features - np.mean(combined_features)) / np.std(combined_features)

        # Append to the list of features
        features.append(normalized_features)

        # Append the label
        labels.append(path.split("/")[-2])
        print(plt.imshow(image_array))
        print(plt.show())
    return features, labels
    


In [23]:
def create_features(image_paths):
    features = []
    labels = []
    for path in image_paths:
        # load the image data
        image_data = imageio.imread("DATASET/1/10.png")
        # extract features using HOG
        fd, hog_image = hog(image_data, orientations=8, pixels_per_cell=(16, 16),
                            cells_per_block=(1, 1), visualize=True)
        features.append(fd)
        labels.append(image_label)
    return features, labels
